version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: library-api-lara
        container_name: laravel-app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"
        environment:
            DB_HOST: db
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: secret
        depends_on:
            - db

    db:
        image: mysql:5.7
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
